# See https://github.com/canonical/gh-jira-sync-bot for advanced config
settings:
  jira_project_key: "ISD"
  
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
    
  add_gh_comment: true
  
  epic_key: ISD-3981
      
  label_mapping:
    bug: Bug
    enhancement: Story
