name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-test:
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@main
    permissions:
      contents: read
      packages: write
      actions: read
    secrets: inherit
    with:
      working-directory: .
