name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@v0.0.1-alpha.5
    permissions:
      actions: read
      contents: write
    with:
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
