name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@0eef5b8cbef3ee74907850f790cab64bcf0499e5 # v1.0.0
    permissions:
      actions: read
      contents: write
    with:
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
