name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    permissions:
      actions: read
      contents: write
    with:
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
