# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules release
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_release.yaml@5f7c5ae8edce88c84ce33ac9674995fa551e3e75  # main
    permissions:
      contents: write
